import { Metadata } from "next"
import "./globals.css"

export const metadata: Metadata = {
  title: {
    absolute: '',
    default: 'Learning about next js',
    template: '%s | code-evolution'
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-200 p-4">
          <p>Header</p>
        </header>
        {children}
        <footer className="bg-green-200 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
